### ISSUE TITLE
use better issue templates

### ISSUE THREAD

**Issue by Miepee** [Dobby233Liu/HATE-UML#14]
### What you want

These dont fit this project at all

**Comment by Dobby233Liu** [comment]
I literally copied these from DOSBox-X
Any suggestions for changes?

**Comment by Miepee** [comment]
- Make `I have searched and didn't find any similar bug report. *` not required
- fix grammar mistakes
- dunno if hate uses any output log
- remove question template and create discussion for it
- remove dosbox-x references

**Comment by Dobby233Liu** [comment]
> * dunno if hate uses any output log

It outputs `HATE.log`

> * remove question template and create discussion for it

✅ 

> * remove dosbox-x references

I don't see any

**Comment by Miepee** [comment]
> I don't see any

You already removed them

**Comment by Miepee** [comment]
This issue can be closed
