### ISSUE TITLE
faq question should be changed

### ISSUE THREAD

**Issue by Miepee** [Dobby233Liu/HATE-UML#2]
> Q: Windows - HATE doesn't start and/or displays an error message instantly.

This is an issue which can happen on all OS, not only windows

**Comment by Dobby233Liu** [comment]
I attempted to solve this issue in the last two commits in master, please check it out

**Comment by Miepee** [comment]
Last two commits is misleading here, as of right now, the last two commits are 46da909908c391e965d9edfaac5ee04c3aad1158 and e352577b2f8c9da2cd7498d14e102521cb126dfd which as far as I can se don't solve the issue.

Read the complete readme again now, only thing I'd change is remove `(unhandled exception crashes are definitely not meaningful in case you wonder)`, as unhandled exception crashes *are* meaningful.

**Comment by Dobby233Liu** [comment]
> Last two commits is misleading here, as of right now, the last two commits are [46da909](https://github.com/Dobby233Liu/HATE-UML/commit/46da909908c391e965d9edfaac5ee04c3aad1158) and [e352577](https://github.com/Dobby233Liu/HATE-UML/commit/e352577b2f8c9da2cd7498d14e102521cb126dfd) which as far as I can se don't solve the issue.

That's before I tried to fix #1

> Read the complete readme again now, only thing I'd change is remove `(unhandled exception crashes are definitely not meaningful in case you wonder)`, as unhandled exception crashes _are_ meaningful.

Fair, reworded in 2ff22dc30ef2c52b5e65e5357f160da5a00464f4
