### ISSUE TITLE
Consider migrating to a cross-platform UI kit

### ISSUE THREAD

**Issue by Dobby233Liu** [Dobby233Liu/HATE-UML#3]
HATE's UI is not like complex or anything. WinForms breaks Unix compatibility

**Comment by Miepee** [comment]
Would recommend using [Eto](https://github.com/picoe/eto) for this, as it's truly native, unlike most other frameworks (like avalonia)

**Comment by Miepee** [comment]
This issue can now be closed after #6

**Comment by Dobby233Liu** [comment]
This caused pain
